export const site = {
  name: "AI For Small Business LLC",
  shortName: "AI For Small Business",
  url: "https://aiforsmall.bz",
  year: 2026,
  contact: {
    phone: "(612) 757-6767",
    phoneTel: "+16127576767",
    email: "jack@aiforsmall.bz",
  },
  promo: {
    headline: "Get Started For Free!",
    body:
      "Our grand opening special is NO SETUP FEE AND you can use our service for 30 days without paying us one penny. If you decide to keep our service, only then you start paying our regular monthly service fee. You decide, no questions asked.",
    note: "Offer expires January 16th, 2026",
  },
  sectionLabel: "Artificial intelligence and software automation",
  hero: {
    line1: "AI for small business",
    line2: "without the headaches",
    sub:
      "AI is here to stay—and you can still be early. We handle the tech so you don't install software, learn new tools, or log into complicated dashboards. It just works.",
  },
  nav: [
    { label: "Services", href: "#services" },
    { label: "Solutions", href: "#solutions" },
    { label: "Studio", href: "#studio" },
    { label: "Pricing", href: "#pricing" },
  ],
  pricingTiers: [
    {
      id: "foundation",
      name: "Foundation",
      badge: "Starter",
      setup: 97,
      monthly: 97,
      firstYear: 97 + 97 * 12,
      blurb: "Contractors running their business from a cell phone—low risk, high reward.",
      features: [
        "Basic CRM to replace spreadsheets",
        "1-page website + lead capture into CRM",
        "Basic lead follow-up (email, 5 touches)",
        "Online booking + appointment reminders (email)",
        "Google Business Profile review & optimization",
        "Monthly performance report",
      ],
      missing: "AI receptionist (available à la carte or in Dominator)",
    },
    {
      id: "growth",
      name: "Growth",
      badge: "Most Popular",
      setup: 297,
      monthly: 297,
      firstYear: 297 + 297 * 12,
      blurb: "Established contractors ready to scale—more automation & follow-up.",
      popular: true,
      features: [
        "Everything in Foundation",
        "Missed-call multi-channel follow-up (SMS, email, voicemail)",
        "5-page website with AI chat widget",
        "Automated review & reputation system",
        "Quote follow-up + reactivation campaigns",
        "Local SEO + AI search optimization",
        "Bi-weekly performance review",
      ],
    },
    {
      id: "dominator",
      name: "Dominator",
      badge: "Scale",
      setup: 997,
      monthly: 997,
      firstYear: 997 + 997 * 12,
      blurb: "Own your market—AI receptionist, social automation, and priority support.",
      features: [
        "Everything in Foundation & Growth",
        "AI receptionist—24/7 answers, qualifies, books",
        "Social media—automated create & post",
        "Full AI-powered local SEO management",
        "Seasonal & promo broadcast campaigns",
        "Review widget + auto-publish",
        "Client dashboard + weekly strategy call",
        "Lead funnels across Meta, Google, X, Reddit, Yahoo, Yelp",
      ],
    },
  ],
} as const;
